name: Actividad 2 GitHub Actions

on:
  push:

jobs:
  tests:
    runs-on: python-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Instalar dependencias
        run: pip install -r requirements.txt

      - name: Ejecutar las pruebas
        run: pytest -v -s